<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>575088bd-c047-4245-a84c-ce45bfaefdcf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
	  <PackageReference Include="Bogus" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	  <PackageReference Include="Microsoft.Identity.Web" />
  </ItemGroup>

</Project>
